# Generated by Django 5.1 on 2024-09-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='supplier_tax_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='tax_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
