# Generated by Django 5.1 on 2024-09-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_invoices_supplier_tax_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
