# Generated by Django 5.1 on 2024-09-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_suppliers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='supplier_name',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
