# Generated by Django 5.1 on 2024-09-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_invoices_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.suppliers', to_field='id_code'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='supplier_vat_number',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='vat_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
