# Generated by Django 5.1 on 2024-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_invoices_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
