# Generated by Django 5.1 on 2024-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_invoices_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
