# Generated by Django 5.1 on 2024-09-08 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_suppliers_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceslines',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoiceslines',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='invoices',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 12, 30)),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 12, 30)),
        ),
    ]
