# Generated by Django 5.1 on 2024-09-08 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_invoiceslines_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2000, 9, 1, 12, 30)),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2000, 9, 1, 12, 30)),
        ),
    ]
