# Generated by Django 5.1 on 2024-09-09 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_suppliers_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
