# Generated by Django 5.1 on 2024-09-09 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_suppliers_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='manually_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceslines',
            name='manually_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='manually_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
